name: ppsflutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.1.7+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  path_provider: ^2.0.8
  network_to_file_image: ^3.1.0
  flutter_html: ^2.2.1
  sqflite: ^2.0.2
  configurable_expansion_tile: ^1.0.0
  flutter_widget_from_html: ^0.6.1
  shared_preferences: ^2.0.12
  #flutter_fullpdfview: any
  audioplayers: ^0.20.1
  video_player: ^2.2.16
  #flutter_webview_plugin: any
  webview_flutter: ^3.0.0
  dio: ^4.0.4
  smooth_page_indicator: ^1.0.0+2
  auto_size_text: ^3.0.0
  html_unescape: ^2.0.0
  #flutter_speed_dial: any
  url_launcher: ^6.0.18
  rect_getter: ^1.1.0
  path: ^1.8.0
  package_info: ^2.0.2
  preload_page_view: ^0.1.6
  disk_space: ^0.2.1
  archive: ^3.1.9
  in_app_update: ^3.0.0
  in_app_review: ^2.0.4
  native_shared_preferences: ^2.0.5
  android_intent: ^2.0.2
  wakelock: ^0.5.2
  cupertino_icons: ^1.0.4
  share: ^2.0.4
  connectivity: ^3.0.6
  printing: ^5.6.6
  dio_http_cache: ^0.3.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  firebase_crashlytics: ^2.5.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.8
  flutter_local_notifications: ^5.0.0

dependency_overrides:
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/db/
    - assets/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: BebasNeue
       fonts:
         - asset: fonts/BebasNeue.otf
     - family: AppleGaramondBold
       fonts:
         - asset: fonts/AppleGaramond-BoldItalic.ttf
     - family: AppleGaramondItalic
       fonts:
         - asset: fonts/AppleGaramond-Italic.ttf
     - family: OpenSans-Regular
       fonts:
        - asset: fonts/OpenSans-Regular.ttf
     - family: OpenSans-Bold
       fonts:
        - asset: fonts/OpenSans-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
